### ISSUE TITLE
Typo in description for example of Object literals in Grammar and types page

### ISSUE THREAD

**Issue by tannerdolby** [mdn/content#1471]
On the [Grammar and types - Object literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Grammar_and_types#object_literals) page, the description for object literals example contains a small typo.

`(carTypes("Honda"));` should have the semi-colon outside of the `<code>` like `(carTypes("Honda"))`;

I'm not sure if the parentheses are required either, but this issue is primarily to fix the semi-colon position.

_Screenshot of object literal description before first example_
<img width="712" alt="Screen Shot 2021-01-18 at 12 49 13 PM" src="https://user-images.githubusercontent.com/48612525/104961642-98928f00-598b-11eb-9c1c-7bc009230347.png">

The semi-colon is used in the above description to separate each of the three elements discussed in the example. Like, `new string, "Saturn"; ...`

**Comment by hamishwillee** [comment]
@tannerdolby Thanks - fixed in #1471. FWIW for this kind of thing you might find it just as easy to make the change in a PR so we can just press the "Submit" button :-). All the context you provided is of course very useful too.

**Comment by tannerdolby** [comment]
@hamishwillee Your welcome! Ok I will keep that in mind moving forward. For simple text changes like this one, I will just submit a PR in the future. Thank you :-)

**Comment by hamishwillee** [comment]
No, thank you!

**Comment by tannerdolby** [comment]
@hamishwillee Is there a reason this PR still isn't merged? I understand you all are probably quite busy, just wanted to check in on this one.

**Comment by chrisdavidmills** [comment]
@tannerdolby looking at the page, the described typo looks like it has been fixed; see https://github.com/mdn/content/commit/6e59a90eb7186b03ed9491871f52a2d89867bff9 for the commit that does this.

In which case, I think we can close this now. 

Feel free to chime in if you still have concerns.

**Comment by tannerdolby** [comment]
@chrisdavidmills Thanks for the heads up. Your right, it looks to have been fixed. I agree with closing and I don't have any further concerns.
