### ISSUE TITLE
DOM reference page sidebar has a different list of interfaces than the body

### ISSUE THREAD

**Issue by ajvsol** [mdn/content#21453]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model

### What specific section or headline is this issue about?

References in the sidebar not being mentioned in the body content, and vice versa

### What information was incorrect, unhelpful, or incomplete?

I'm trying to learn the DOM and having two different lists is rather confusing, I'm not sure which is the real source of truth. For example `URL` is mentioned in the body only, and `StaticRange` is mentioned in the sidebar only.

### What did you expect to see?

One of the lists should contain all the interfaces of the other.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/document_object_model`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/document_object_model/index.md
* Last commit: https://github.com/mdn/content/commit/1511e914c6b1ce6f88056bfefd48a6aa585cebce
* Document last modified: 2022-09-09T05:10:34.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks @ajvsol . 
In fact, neither is a source of truth - that can only be the specification, and MDN will always lag whatever browser vendors are doing. But yes, the sidebar and the page should match if at all possible. Would you like to make them do so? Otherwise this will wait until it becomes a priority for someone.

**Comment by wbamberg** [comment]
The sidebar is driven by this file: https://github.com/mdn/content/blob/main/files/jsondata/GroupData.json and in particular https://github.com/mdn/content/blob/31c5401d7aa2b7f5146363cd9bf02a2221a5b20b/files/jsondata/GroupData.json#L297-L352. The list in the page is "maintained" manually.

Of the two, the list in GroupData is more likely to be right (e.g. the one you mentioned, `URL`, belongs in the URL API: https://developer.mozilla.org/en-US/docs/Web/API/URL_API (and is also listed there).

As Hamish says though: a page like this (an "API overview page") generally maps to a specification, and both lists should really reflect the interfaces defined in that specification, which in this case is the IDL list of interfaces at https://dom.spec.whatwg.org/#idl-index.

It would be cool if we could build both the sidebar and this section of the page from the IDL. We're not that far really:

yari builder could:
- see that this is a `web-api-overview` page
- fetch the spec URL from front matter/BCD
- use that to fetch the IDL from webref/idl
- use that to retrieve the list of interfaces

For the page, one obvious omission is the prose summary description of the interface. To get that to work would need a reliably-accessible "prose summary" for pages. Another is that you'd need some backup for nonstandard things that you wanted to list. And I expect there would be lots of messy exceptions to work through.

But most of the pieces are there, or almost there.  It's not that different from this: https://github.com/mdn/yari/pull/7227#issuecomment-1264230886.

**Comment by bsmth** [comment]
Hi @ajvsol, thanks for raising an issue. It looks like Will and Hamish have answered your question so I'm going to close this one for now. If you think this is a mistake, feel free to comment and let us know.

Thank you :)

**Comment by hamishwillee** [comment]
@bsmth Reopening. This should be fixed by a person or a system. It is hard to get right manually, but no harm for us to try.

**Comment by teoli2003** [comment]
To fix this manually, as we won't have the perfect solution for a long time, I opened two PR: one to add missing entries on the page, and the other for a missing entry in the sidebar.

NodeFilter is still missing from the sidebar, but we don't have a page for it.

DOM is stable-enough so we shouldn't  have to manually sync it too often
